import { useCallback, useEffect, useState } from "react";
import { Activity, ArrowDownToLine, ArrowUpFromLine, CalendarDays } from "lucide-react";
import { analysisApi, dashboardApi } from "../api";
import { AccessByDayChart, AccessByHourChart } from "../components/Charts";
import { EmptyState, ErrorState, LoadingState, MetricCard, PageHeader } from "../components/UI";
import type { AccessByDay, AccessByHour, FrequentPerson, PatternSummary } from "../types";
import { daysBefore, errorMessage, formatHour, formatNumber, today } from "../utils";

export function AnalyticsPage() {
  const [hasta, setHasta] = useState(today());
  const [desde, setDesde] = useState(daysBefore(today(), 29));
  const [data, setData] = useState<{ hours: AccessByHour[]; days: AccessByDay[]; frequent: FrequentPerson[]; patterns: PatternSummary } | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [hours, days, frequent, patterns] = await Promise.all([dashboardApi.byHour(hasta), dashboardApi.byDay(desde, hasta), dashboardApi.frequent(desde, hasta, 10), analysisApi.patterns(desde, hasta)]); setData({ hours, days, frequent, patterns }); } catch (err) { setError(errorMessage(err)); } finally { setLoading(false); } }, [desde, hasta]);
  useEffect(() => { void load(); }, [load]);

  return <div className="page-stack"><PageHeader title="Analítica de accesos" subtitle="Patrones temporales procesados directamente sobre los registros históricos" actions={<div className="range-controls"><label>Desde<input type="date" value={desde} max={hasta} onChange={(e) => setDesde(e.target.value)} /></label><label>Hasta<input type="date" value={hasta} min={desde} onChange={(e) => setHasta(e.target.value)} /></label></div>} />{loading ? <LoadingState label="Calculando indicadores…" /> : error || !data ? <ErrorState message={error || "No se pudo cargar el análisis."} onRetry={load} /> : <><section className="metrics-grid"><MetricCard label="Pico general" value={formatHour(data.patterns.horaPicoGeneral)} helper={`${formatNumber(data.patterns.cantidadHoraPicoGeneral)} accesos`} icon={Activity} /><MetricCard label="Pico entradas" value={formatHour(data.patterns.horaPicoEntradas)} helper={`${formatNumber(data.patterns.cantidadHoraPicoEntradas)} eventos`} icon={ArrowDownToLine} tone="green" /><MetricCard label="Pico salidas" value={formatHour(data.patterns.horaPicoSalidas)} helper={`${formatNumber(data.patterns.cantidadHoraPicoSalidas)} eventos`} icon={ArrowUpFromLine} tone="indigo" /><MetricCard label="Día predominante" value={data.patterns.diaSemanaMayorActividad || "—"} helper={data.patterns.fechaMayorActividad || "Sin actividad"} icon={CalendarDays} tone="slate" /></section><section className="dashboard-grid"><article className="panel span-2"><div className="panel-heading"><div><span className="eyebrow">DÍA SELECCIONADO</span><h3>Distribución por hora</h3></div><span className="panel-note">{hasta}</span></div><AccessByHourChart data={data.hours} /></article><article className="panel"><div className="panel-heading"><div><span className="eyebrow">PERIODO</span><h3>Actividad por día</h3></div></div><AccessByDayChart data={data.days} /></article></section><article className="panel"><div className="panel-heading"><div><span className="eyebrow">FRECUENCIA</span><h3>Personas con mayor actividad</h3></div><span className="panel-note">Top 10</span></div>{data.frequent.length ? <div className="table-scroll"><table><thead><tr><th>Posición</th><th>Persona</th><th>Código</th><th>Accesos</th></tr></thead><tbody>{data.frequent.map((person, index) => <tr key={person.personaId}><td><span className="rank">{index + 1}</span></td><td><strong>{person.nombre}</strong></td><td>{person.codigoBiometrico}</td><td><strong>{formatNumber(person.cantidadAccesos)}</strong></td></tr>)}</tbody></table></div> : <EmptyState />}</article></>}</div>;
}
