import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Clock3, Moon, Repeat2 } from "lucide-react";
import { analysisApi } from "../api";
import { ErrorState, LoadingState, MetricCard, PageHeader, Pagination, StatusBadge, EmptyState } from "../components/UI";
import type { Anomaly, AnomalySummary, PageResponse } from "../types";
import { daysBefore, errorMessage, formatDateTime, formatNumber, today } from "../utils";

const anomalyTypes = ["ACCESO_NOCTURNO", "ACCESO_TEMPRANO", "ACCESO_TARDIO", "ACCESOS_REPETITIVOS", "RECHAZOS_REPETITIVOS", "DESVIACION_HORARIO"];

export function AnomaliesPage() {
  const [hasta, setHasta] = useState(today()); const [desde, setDesde] = useState(daysBefore(today(), 29));
  const [tipo, setTipo] = useState(""); const [personaId, setPersonaId] = useState(""); const [page, setPage] = useState(0);
  const [data, setData] = useState<{ summary: AnomalySummary; anomalies: PageResponse<Anomaly> } | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [summary, anomalies] = await Promise.all([analysisApi.anomalySummary(desde, hasta), analysisApi.anomalies(desde, hasta, page, 20, tipo, personaId)]); setData({ summary, anomalies }); } catch (err) { setError(errorMessage(err, "No se pudieron cargar las anomalías.")); } finally { setLoading(false); } }, [desde, hasta, page, tipo, personaId]);
  useEffect(() => { void load(); }, [load]);

  return <div className="page-stack"><PageHeader title="Anomalías" subtitle="Hallazgos generados por reglas temporales y comportamiento habitual" /><div className="filters-bar"><label>Desde<input type="date" value={desde} max={hasta} onChange={(e) => { setDesde(e.target.value); setPage(0); }} /></label><label>Hasta<input type="date" value={hasta} min={desde} onChange={(e) => { setHasta(e.target.value); setPage(0); }} /></label><label>Tipo<select value={tipo} onChange={(e) => { setTipo(e.target.value); setPage(0); }}><option value="">Todos</option>{anomalyTypes.map((value) => <option key={value}>{value}</option>)}</select></label><label>Persona ID<input type="number" min="1" value={personaId} placeholder="Todas" onChange={(e) => { setPersonaId(e.target.value); setPage(0); }} /></label></div>{loading ? <LoadingState label="Evaluando reglas analíticas…" /> : error || !data ? <ErrorState message={error || "No se encontró información."} onRetry={load} /> : <><section className="metrics-grid"><MetricCard label="Total anomalías" value={formatNumber(data.summary.totalAnomalias)} helper={`${formatNumber(data.summary.registrosAnalizados)} registros analizados`} icon={AlertTriangle} tone="red" /><MetricCard label="Accesos nocturnos" value={formatNumber(data.summary.accesosNocturnos)} helper="00:00 a 04:59" icon={Moon} tone="indigo" /><MetricCard label="Eventos repetitivos" value={formatNumber(data.summary.accesosRepetitivos)} helper="Ventana de 5 minutos" icon={Repeat2} tone="amber" /><MetricCard label="Desviaciones" value={formatNumber(data.summary.desviacionesHorario)} helper="Respecto al patrón habitual" icon={Clock3} tone="slate" /></section><article className="panel"><div className="panel-heading"><div><span className="eyebrow">RESULTADOS</span><h3>Eventos detectados</h3></div><span className="panel-note">{formatNumber(data.anomalies.totalElements)} hallazgos</span></div>{data.anomalies.content.length ? <><div className="table-scroll"><table><thead><tr><th>Fecha y hora</th><th>Persona</th><th>Tipo</th><th>Nivel</th><th>Descripción</th></tr></thead><tbody>{data.anomalies.content.map((item) => <tr key={`${item.tipo}-${item.registroAccesoId}`}><td>{formatDateTime(item.fechaHora)}</td><td><div className="table-person"><strong>{item.nombrePersona}</strong><small>{item.codigoPersona}</small></div></td><td>{item.tipo.replaceAll("_", " ")}</td><td><StatusBadge value={item.nivel} /></td><td className="description-cell">{item.descripcion}</td></tr>)}</tbody></table></div><Pagination page={data.anomalies.number} totalPages={data.anomalies.totalPages} onChange={setPage} /></> : <EmptyState message="No se detectaron anomalías con estos filtros." />}</article></>}</div>;
}
